jobs:
- job: install_services
  displayName: Install services and needed apt-packages
  steps:
  - script: git status
    displayName: check git status
  - script: sudo apt-get install mongodb
    displayName: install mongodb
  - script: sudo systemctl start mongodb && sudo systemctl status mongodb
    displayName: start mongodb
  - script: sudo apt-get install xvfb
    displayName: install xvfb
  - script: Xvfb :99 &
    env:
      DISPLAY: ":99"
    displayName: start xvfb
  - script: sudo apt-get install qtbase5-dev
    displayName: install qtbase5-dev

