variables:
  MPLBACKEND: Qt5Agg
  BS_PROFILE: collection
  TEST_PROFILE: default
  BS_ENV_VERSION: 2019C3.0.1
  _CONDA_CHANNEL: nsls2forge
  OPHYD_CONTROL_LAYER: pyepics

jobs:
- job: install_services
  displayName: Install services and needed apt-packages
  steps:
  - script: git status
    displayName: check git status
  - script: sudo apt-get install mongodb
    displayName: install mongodb
  - script: sudo systemctl start mongodb && sudo systemctl status mongodb
    displayName: start mongodb
  - script: sudo apt-get install xvfb
    displayName: install xvfb
  # from https://developercommunity.visualstudio.com/content/problem/336288/headless-testing-using-xvfb-on-hosted-ubuntu-1604.html
  - script: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
    displayName: start xvfb
  - script: sudo apt-get install qtbase5-dev
    displayName: install qtbase5-dev

  ##### Common steps #####
  - script: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    displayName: download miniconda
  - script: sh ./miniconda.sh -b -p ~/mc
    displayName: install miniconda
  - script: source ~/mc/etc/profile.d/conda.sh  # this makes all conda vars available
    displayName: source conda vars
  - script: conda update conda --yes
    displayName: update conda
  # pyOlog config:
  - script: cp -v pyOlog-test.conf ~/pyOlog.conf
    displayName: copy pyOlog config
  # Databroker config:
  - script: mkdir -v -p ~/.config/databroker/ && cp -v databroker.yml ~/.config/databroker/$(git config --get remote.origin.url | awk -F'[/-]' '{print tolower($6)}').yml
    displayName: copy databroker config
